# goal
int32 tile_index      # 타일 번호
int8 tile_type        # 타일 타입
---
# result
bool success
string message
---
# Feedback
int32 step
float32 progress
string state
float32 target_x
float32 target_y
float32 target_z